/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package social.network2.pkg0;

import java.io.File;
import java.io.FileInputStream;
import java.util.HashMap;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Cool Dev
 */
public class HelloWorld extends javax.swing.JFrame {

    /**
     * Creates new form HelloWorld
     */
    public HelloWorld() {
        initComponents();
    }
     
    /*
     private int validation()
    {
        String password = new String(jPasswordField1.getPassword());
        String username = jTextField1.getText()+".txt";
        File f = new File(username);
        if(f.exists())
        {
            if(username.equals("Enter your username.txt"))
                return 2;
            JOptionPane.showMessageDialog(null,"Username Already Exists","ERROR",JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        else
        {
            if((!jTextField1.getText().isEmpty())&&(!password.isEmpty())&&(!jTextField2.getText().isEmpty()))
            {
                return 1;
            }
            else
                return 2;
        }
    }
    
    
    */
  //  &&(!password.isEmpty())
    //!tf_username.getText().isEmpty())&&
      
    private int validation(){
    
        String password = new String(pf_password.getPassword());
        
        
       // JOptionPane.showMessageDialog(null,"tf.getText()","ERROR",JOptionPane.ERROR_MESSAGE);
       // System.out.println(tf_username.getText());
        if(!tf_username.getText().isEmpty())
        {
            String userfile = tf_username.getText()+".txt";
            File file = new File(userfile);
            if(file.exists())
            {
                HashMap <String,String> datamap = new HashMap<String,String>();
                Properties properties = new Properties();
                try
                {
                    FileInputStream f1 = new FileInputStream(userfile);
                    properties.load(f1);
                    f1.close();
                    for (String key : properties.stringPropertyNames()) 
                    {
                        datamap.put(key, properties.get(key).toString());
                    }
                    String s = datamap.get("Password").toString();
                    if(s.equals(new String(pf_password.getPassword())))
                    {
                        return 1;//password matches
                    }
                    else
                    {
                        return 2;//password does not matches
                    }
                    
                }
                catch(Exception e)
                {
                       //JOptionPane.showMessageDialog(null,"Could not find File","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
            else
            {
                return 0;//No such user exists
            }
        }
        else{
            return 3;//some field is empty
        }
        
        return 0;
    }
    
    
    
    
    
    private static String username;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bt_Register = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pf_password = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        bt_login = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel9.setText("COOL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 110, 80));

        jLabel12.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel12.setText("If u Want to be a part of our Journey");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 340, 70));

        jLabel13.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel13.setText("<html>Technology is giving  </br>life the Potential to flourish like never before</br> or to Self Destruct.</br> </html>");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 230, 190));

        jLabel14.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel14.setText("JOIN US");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 90, 60));

        jLabel15.setFont(new java.awt.Font("Kristen ITC", 0, 18)); // NOI18N
        jLabel15.setText("Let's make a Difference");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 260, 80));

        bt_Register.setBackground(new java.awt.Color(0, 0, 0));
        bt_Register.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        bt_Register.setForeground(new java.awt.Color(255, 255, 255));
        bt_Register.setText("REGISTER");
        bt_Register.setBorder(null);
        bt_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_RegisterMouseEntered(evt);
            }
        });
        bt_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RegisterActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 50));

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel19.setText("Be Cool");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 590));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ZONE");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 80));

        jLabel10.setFont(new java.awt.Font("Kristen ITC", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sign IN ");
        jLabel10.setToolTipText("");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 70));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 270, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 270, 40));

        pf_password.setBackground(new java.awt.Color(0, 0, 0));
        pf_password.setForeground(new java.awt.Color(255, 255, 255));
        pf_password.setText("password");
        pf_password.setBorder(null);
        pf_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pf_passwordFocusGained(evt);
            }
        });
        pf_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pf_passwordMouseClicked(evt);
            }
        });
        jPanel2.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 280, 20));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("USER NAME");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 270, 30));

        tf_username.setBackground(new java.awt.Color(0, 0, 0));
        tf_username.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tf_username.setForeground(new java.awt.Color(255, 255, 255));
        tf_username.setText("Enter your Username");
        tf_username.setBorder(null);
        tf_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_usernameMouseClicked(evt);
            }
        });
        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        jPanel2.add(tf_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 330, 30));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, 40));

        bt_login.setBackground(new java.awt.Color(0, 0, 0));
        bt_login.setFont(new java.awt.Font("Kristen ITC", 1, 14)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setText("LOGIN");
        bt_login.setBorder(null);
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
        });
        bt_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loginActionPerformed(evt);
            }
        });
        jPanel2.add(bt_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 120, 50));

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Be Uneek");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 430, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pf_passwordMouseClicked
        // TODO add your handling code here:
        pf_password.setText("");
    }//GEN-LAST:event_pf_passwordMouseClicked

    private void tf_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_usernameMouseClicked
        // TODO add your handling code here:
        tf_username.setText("");
    }//GEN-LAST:event_tf_usernameMouseClicked

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void bt_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RegisterMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bt_RegisterMouseClicked

    private void bt_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RegisterActionPerformed
        // TODO add your handling code here:
        Register newuser = new Register(username);
       // HelloWorld main = new HelloWorld();
        newuser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bt_RegisterActionPerformed

    private void bt_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loginActionPerformed
        // TODO add your handling code here:
        
        //Checking the Authentication and connecting if everything matches
          int passcheck = 0;//password checker which  is valid till 3 trials
          int check = validation();
        if(check == 1)
        {
            username = tf_username.getText();
            setVisible(false);
            Login profile = new Login(username);
          //  profile.setSize(getSize());
            profile.setLocationRelativeTo(null);
            profile.setVisible(true);
            this.dispose();
        }
        if(check==0){
            
            JOptionPane.showMessageDialog(null,"No Such User Exists !","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        if(check==2){
            passcheck++;
            JOptionPane.showMessageDialog(null,"Wrong Password, Try Again","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        if(check==3){
        
            JOptionPane.showMessageDialog(null,"Please fill the empty fields","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        
        if(passcheck==3){
            
            JOptionPane.showMessageDialog(null,"Sorry,U Exceeded the Login Limit","ERROR",JOptionPane.ERROR_MESSAGE);
            
            
        }
        
        
    }//GEN-LAST:event_bt_loginActionPerformed

    private void pf_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_passwordFocusGained
        // TODO add your handling code here:
        pf_password.setText("");
    }//GEN-LAST:event_pf_passwordFocusGained

    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bt_loginMouseClicked

    private void bt_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RegisterMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_RegisterMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelloWorld.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HelloWorld().setVisible(true);
            }
        });
    }
    
 //   private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
 //       jTextField2.setText(" ");
 //   }                                        

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        jTextField1.setText("");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
  
        // TODO add your handling code here:
        
        
    }   
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Register;
    private javax.swing.JButton bt_login;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables

    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
  //  private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
  //  private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
  //  private javax.swing.JTextField jTextField2;



}


